# This is a basic workflow to help you get started with Actions

name: PRUEBA

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      platform: "aws"
      region: "us-eats"
      account: "Richi"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: "display message"
       run:
        echo "Hola mundo"
     - name: "Variables"
       if: ${{env.platform=='azure'}}
       run: |
          echo " la platform: ${{env.platform}}"
          echo "region: ${{env.region}}"
          echo "account: ${{env.account}}"
    